steps:
  # 构建镜像
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/stock-data-api', '.']
  
  # 推送镜像
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/stock-data-api']
  
  # 部署到 Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'stock-data-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/stock-data-api'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-east1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'SUPABASE_URL=${_SUPABASE_URL},SUPABASE_KEY=${_SUPABASE_KEY}'

images:
  - 'gcr.io/$PROJECT_ID/stock-data-api'

substitutions:
  _SUPABASE_URL: '' # 在Cloud Build触发器中设置
  _SUPABASE_KEY: '' # 在Cloud Build触发器中设置

options:
  logging: CLOUD_LOGGING_ONLY