name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authorize Docker push
      run: gcloud auth configure-docker

    - name: Build and push
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/stock-data-api .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/stock-data-api

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy stock-data-api \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/stock-data-api \
          --platform managed \
          --region asia-east1 \
          --allow-unauthenticated \
          --set-env-vars="SUPABASE_URL=${{ secrets.SUPABASE_URL }},SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}"